### ISSUE TITLE
Corrupt config causes crash also appearing in wrong directory

### ISSUE THREAD

**Issue by james090500** [MinecraftCapes/minecraftcapes-mod#3]
https://github.com/MinecraftCapes/minecraftcapes-mod/blob/build-1.21/common/src/main/java/net/minecraftcapes/config/MinecraftCapesConfig.java#L86

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'minecraftcapes'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
at net.minecraft.class_310.<init>(class_310.java:477)
at net.minecraft.client.main.Main.main(Main.java:239)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
at com.google.gson.Gson.fromJson(Gson.java:1227)
at com.google.gson.Gson.fromJson(Gson.java:1137)
at com.google.gson.Gson.fromJson(Gson.java:1075)
at net.minecraftcapes.config.MinecraftCapesConfig.loadConfig(MinecraftCapesConfig.java:86)
at net.minecraftcapes.MinecraftCapes.onEnable(MinecraftCapes.java:41)
at net.minecraftcapes.fabric.FabricClient.onInitializeClient(FabricClient.java:20)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
... 6 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386)
... 13 more
```

**Comment by james090500** [comment]
This will be fixed
